#!/bin/bash

source $(dirname $0)/lib/debug_functions
source $(dirname $0)/lib/version

cd $(dirname $0)/..

operator-sdk build quay.io/submariner/submariner-operator:$VERSION --verbose --go-build-args "-ldflags -s -ldflags -w"
